/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author carol
 */
public class Gestion_Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Gestion_Clientes
     */
    public Gestion_Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Multimedia/clienteFrame.png"));
        Image image = icon.getImage();
        Desk1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,Desk1.getWidth(),Desk1.getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMmascotasXclientes = new javax.swing.JMenu();
        jMregistroClientes = new javax.swing.JMenuItem();
        jMbusquedaYgedstionClientes = new javax.swing.JMenuItem();
        jMclientesXnombre = new javax.swing.JMenu();
        jMmascotasPorCliente = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMlistaClientes = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("GRUPO 75");

        javax.swing.GroupLayout Desk1Layout = new javax.swing.GroupLayout(Desk1);
        Desk1.setLayout(Desk1Layout);
        Desk1Layout.setHorizontalGroup(
            Desk1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1218, Short.MAX_VALUE)
        );
        Desk1Layout.setVerticalGroup(
            Desk1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        jMmascotasXclientes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMmascotasXclientes.setForeground(new java.awt.Color(51, 51, 51));
        jMmascotasXclientes.setText("        Formulario de Clientes        ");
        jMmascotasXclientes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMregistroClientes.setText("Registro de Clientes");
        jMregistroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMregistroClientesActionPerformed(evt);
            }
        });
        jMmascotasXclientes.add(jMregistroClientes);

        jMbusquedaYgedstionClientes.setText("Busqueda y Gestion de Clientes");
        jMbusquedaYgedstionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMbusquedaYgedstionClientesActionPerformed(evt);
            }
        });
        jMmascotasXclientes.add(jMbusquedaYgedstionClientes);

        jMenuBar1.add(jMmascotasXclientes);

        jMclientesXnombre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMclientesXnombre.setText("         Consultas        ");
        jMclientesXnombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMclientesXnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMclientesXnombreActionPerformed(evt);
            }
        });

        jMmascotasPorCliente.setText("Buscar Pacientes por Cliente");
        jMmascotasPorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmascotasPorClienteActionPerformed(evt);
            }
        });
        jMclientesXnombre.add(jMmascotasPorCliente);

        jMenuItem2.setText("Buscar Clientes por Nombre");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMclientesXnombre.add(jMenuItem2);

        jMlistaClientes.setText("Lista de Clientes");
        jMlistaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMlistaClientesActionPerformed(evt);
            }
        });
        jMclientesXnombre.add(jMlistaClientes);

        jMenuBar1.add(jMclientesXnombre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desk1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMregistroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMregistroClientesActionPerformed
        Registro_Clientes rc = new Registro_Clientes();
        rc.setVisible(true);
        Desk1.add(rc);
        Desk1.moveToFront(rc);
    }//GEN-LAST:event_jMregistroClientesActionPerformed

    private void jMbusquedaYgedstionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMbusquedaYgedstionClientesActionPerformed
        Busqueda_Gestion_Clientes bgc = new Busqueda_Gestion_Clientes();
        bgc.setVisible(true);
        Desk1.add(bgc);
        Desk1.moveToFront(bgc);
    }//GEN-LAST:event_jMbusquedaYgedstionClientesActionPerformed

    private void jMclientesXnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMclientesXnombreActionPerformed
//        Desk1.removeAll();
//        Desk1.repaint();
//        BusquedaClientesPorNombre cxn = new BusquedaClientesPorNombre();
//        cxn.setVisible(true);
//        Desk1.add(cxn);
//        Desk1.moveToFront(cxn);
    }//GEN-LAST:event_jMclientesXnombreActionPerformed

    private void jMmascotasPorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmascotasPorClienteActionPerformed
        MascotasPorCliente mc = new MascotasPorCliente();
        mc.setVisible(true);
        Desk1.add(mc);
        Desk1.moveToFront(mc);
    }//GEN-LAST:event_jMmascotasPorClienteActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Desk1.removeAll();
        Desk1.repaint();
        BusquedaClientesPorNombre cxn = new BusquedaClientesPorNombre();
        cxn.setVisible(true);
        Desk1.add(cxn);
        Desk1.moveToFront(cxn);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMlistaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMlistaClientesActionPerformed
        ListaClientes lc = new ListaClientes();
        lc.setVisible(true);
        Desk1.add(lc);
        Desk1.moveToFront(lc);
    }//GEN-LAST:event_jMlistaClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desk1;
    private javax.swing.JMenuItem jMbusquedaYgedstionClientes;
    private javax.swing.JMenu jMclientesXnombre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMlistaClientes;
    private javax.swing.JMenuItem jMmascotasPorCliente;
    private javax.swing.JMenu jMmascotasXclientes;
    private javax.swing.JMenuItem jMregistroClientes;
    // End of variables declaration//GEN-END:variables
}
