/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

//import vistas.Lista_PacientesXtratamientos;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author carol
 */
public class Gestion_Tratamientos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Gestion_Tratamientos
     */
    public Gestion_Tratamientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Multimedia/tratamientoFrame.png"));
        Image image = icon.getImage();
        Desk1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,Desk1.getWidth(),Desk1.getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMregistro = new javax.swing.JMenuItem();
        jMbusquedaYgestion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMpacientesXtratamientos = new javax.swing.JMenuItem();
        jMlistaTratamientos = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("GRUPO 75");

        javax.swing.GroupLayout Desk1Layout = new javax.swing.GroupLayout(Desk1);
        Desk1.setLayout(Desk1Layout);
        Desk1Layout.setHorizontalGroup(
            Desk1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1217, Short.MAX_VALUE)
        );
        Desk1Layout.setVerticalGroup(
            Desk1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );

        jMenu1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu1.setText("    Formulario de Tratamientos    ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMregistro.setText("Registro de Tratamientos");
        jMregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMregistroActionPerformed(evt);
            }
        });
        jMenu1.add(jMregistro);

        jMbusquedaYgestion.setText("Busqueda y Gestion de Tratamientos");
        jMbusquedaYgestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMbusquedaYgestionActionPerformed(evt);
            }
        });
        jMenu1.add(jMbusquedaYgestion);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu2.setText("    Consultas    ");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMpacientesXtratamientos.setText("Buscar Pacientes por Tratamientos");
        jMpacientesXtratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMpacientesXtratamientosActionPerformed(evt);
            }
        });
        jMenu2.add(jMpacientesXtratamientos);

        jMlistaTratamientos.setText("Listado de Tratamientos");
        jMlistaTratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMlistaTratamientosActionPerformed(evt);
            }
        });
        jMenu2.add(jMlistaTratamientos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desk1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desk1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMregistroActionPerformed
        RegistroTratamientos rt = new RegistroTratamientos();
        rt.setVisible(true);
        Desk1.add(rt);
        Desk1.moveToFront(rt);
    }//GEN-LAST:event_jMregistroActionPerformed

    private void jMbusquedaYgestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMbusquedaYgestionActionPerformed
        Busqueda_Gestion_Tratamientos bgt = new Busqueda_Gestion_Tratamientos();
        bgt.setVisible(true);
        Desk1.add(bgt);
        Desk1.moveToFront(bgt);
    }//GEN-LAST:event_jMbusquedaYgestionActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        //        Lista_pacientesXtratamientos lpt = new Lista_pacientesXtratamientos();
        //        lpt.setVisible(true);
        //        Desk1.add(lpt);
        //        Desk1.moveToFront(lpt);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMpacientesXtratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMpacientesXtratamientosActionPerformed
        Lista_pacientesXtratamientos lpt = new Lista_pacientesXtratamientos();
        lpt.setVisible(true);
        Desk1.add(lpt);
        Desk1.moveToFront(lpt);
    }//GEN-LAST:event_jMpacientesXtratamientosActionPerformed

    private void jMlistaTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMlistaTratamientosActionPerformed
        ListaTratamientos lt = new ListaTratamientos();
        lt.setVisible(true);
        Desk1.add(lt);
        Desk1.moveToFront(lt);
    }//GEN-LAST:event_jMlistaTratamientosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desk1;
    private javax.swing.JMenuItem jMbusquedaYgestion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMlistaTratamientos;
    private javax.swing.JMenuItem jMpacientesXtratamientos;
    private javax.swing.JMenuItem jMregistro;
    // End of variables declaration//GEN-END:variables
}
